import LocalStorageStore from './local-storage-store'
export default LocalStorageStore('enemies', {
	'simple green guy': {
		graphicStill: 'original enemy green',
		name: 'simple green guy',
		maxVelocity: 5,
		jumpVelocity: 7,
		gravityMultiplier: 1,
		fallDamageMultiplier: 0.5,
		dps: 120,
		dpsToPlayers: 50,
		maxHealth: 100,
		score: 1,
	},
	'mr smiley': {
		graphicStill: 'mr smiley',
		name: 'mr smiley',
		maxVelocity: 2,
		jumpVelocity: 12,
		gravityMultiplier: 1,
		fallDamageMultiplier: 1,
		dps: 120,
		dpsToPlayers: 50,
		maxHealth: 5000,
		score: 10,
	},
	'simple black guy': {
		graphicStill: 'original enemy black',
		name: 'simple black guy',
		maxVelocity: 5,
		jumpVelocity: 7,
		gravityMultiplier: 1,
		fallDamageMultiplier: 0.5,
		dps: 120,
		maxHealth: 100,
		dpsToPlayers: 50,
		score: 1,
	},
})
